[package]
name = "mx-plug-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mx-plug-shared = { path = "../shared" }
base64 = "0.21.4"
serde_json = "1.0.107"
